hanyang-art-therapy/backend

.gitignore
src/main/java/com/hanyang/arttherapy/common/exception/CustomException.java
src/main/java/com/hanyang/arttherapy/common/exception/GlobalExceptionHandler.java
src/main/java/com/hanyang/arttherapy/common/exception/exceptionType/CommonExceptionType.java
src/main/java/com/hanyang/arttherapy/common/exception/exceptionType/ExceptionType.java
src/main/resources/application.yml

- closed #5
- 공통 예외 처리 로직
- .gitignore 수정
- application.yml 공유
- .gitkeep 파일 삭제
- 해당사항 없음

[FEAT] 공통 예외 구현

---

src/main/java/com/hanyang/arttherapy/HanyangArttherapyApplication.java
src/main/java/com/hanyang/arttherapy/common/config/AppConfig.java
src/main/java/com/hanyang/arttherapy/common/entity/BaseEntity.java
src/main/java/com/hanyang/arttherapy/common/exception/GlobalExceptionHandler.java
src/main/java/com/hanyang/arttherapy/common/exception/exceptionType/FileSystemExceptionType.java
src/main/java/com/hanyang/arttherapy/common/init/DirectoryInit.java
src/main/java/com/hanyang/arttherapy/controller/FileController.java
src/main/java/com/hanyang/arttherapy/domain/Files.java
src/main/java/com/hanyang/arttherapy/domain/enums/FilesType.java
src/main/java/com/hanyang/arttherapy/dto/response/FileResponseDto.java
src/main/java/com/hanyang/arttherapy/dto/response/FileResponseListDto.java
src/main/java/com/hanyang/arttherapy/repository/FilesRepository.java
src/main/java/com/hanyang/arttherapy/service/FileStorageService.java
src/main/java/com/hanyang/arttherapy/service/FileStorageUtils.java
src/main/java/com/hanyang/arttherapy/service/LocalFileStorageService.java
src/main/resources/application-local.yml
src/main/resources/application.yml

- closed #7
- 파일 타입에 따른 디렉토리 초기화
- 파일 업로드 처리
- 파일명 중복 방지를 위한 리네이밍
- 파일 유효성 검증(파일 용량, 확장자 등)
- 파일 시스템 예외 처리 추가
- 실패 응답 처리
- Postman 요청 성공

[FEAT] 파일 업로드

---

src/main/java/com/hanyang/arttherapy/repository/FilesRepository.java

- closed #17
- 매개변수 오타 수정
- 해당 사항 없음

[RENAME] 매개변수 오타 수정

---

src/main/java/com/hanyang/arttherapy/common/exception/exceptionType/ArtistsException.java
src/main/java/com/hanyang/arttherapy/controller/ArtistController.java
src/main/java/com/hanyang/arttherapy/domain/Artists.java
src/main/java/com/hanyang/arttherapy/dto/request/ArtistRequestDto.java
src/main/java/com/hanyang/arttherapy/dto/response/ArtistResponseDto.java
src/main/java/com/hanyang/arttherapy/dto/response/ArtistResponseListDto.java
src/main/java/com/hanyang/arttherapy/repository/ArtistsRepository.java
src/main/java/com/hanyang/arttherapy/service/ArtistsService.java

- closed #19 
- 새로운 작가 등록
- 입력 값 검증 : 학번 중복 검사, 유효한 작가 ID 확인
- 실패 응답 처리
-  Postman 성공

[FEAT] 작가 등록

---

src/main/java/com/hanyang/arttherapy/controller/ArtistController.java
src/main/java/com/hanyang/arttherapy/service/ArtistsService.java

- closed #20 
- 작가 전체 조회
- 작가 개별 조회
- 실패 응답 처리
- Postman 성공

[FEAT] 작가 조회

---

src/main/java/com/hanyang/arttherapy/controller/ArtistController.java
src/main/java/com/hanyang/arttherapy/service/ArtistsService.java

- closed #21 
- 작가 정보 업데이트
- 입력 값 검증 : 학번 중복 여부, 유효한 작가 ID 확인
- 실패 응답 처리
- Postman 성공

[FEAT] 작가 정보 수정

---

src/main/java/com/hanyang/arttherapy/controller/ArtistController.java
src/main/java/com/hanyang/arttherapy/service/ArtistsService.java

- closed #22 
- 작가 삭제 기능
- 입력 값 검증 : 유효한 작가 ID 확인
- 실패 응답 처리
- Postman 성공

[FEAT] 작가 삭제

---

src/main/java/com/hanyang/arttherapy/repository/ArtistsRepository.java
src/main/java/com/hanyang/arttherapy/service/ArtistsService.java
src/test/java/com/hanyang/arttherapy/service/ArtistsServiceTest.java

- closed #27 
- 작가 등록 테스트
- 작가 수정 테스트
- 작가 개별 조회 테스트
- 작가 삭제 테스
- 테스트 결과 성공

[TEST] 작가 기능 테스트

---

gradlew
gradlew.bat
src/main/java/com/hanyang/arttherapy/controller/ArtsController.java
src/main/java/com/hanyang/arttherapy/controller/ReviewController.java
src/main/java/com/hanyang/arttherapy/domain/ArtArtistRel.java
src/main/java/com/hanyang/arttherapy/domain/Artists.java
src/main/java/com/hanyang/arttherapy/domain/Arts.java
src/main/java/com/hanyang/arttherapy/domain/Galleries.java
src/main/java/com/hanyang/arttherapy/domain/Review.java
src/main/java/com/hanyang/arttherapy/domain/enums/ArtType.java
src/main/java/com/hanyang/arttherapy/dto/response/ArtsDetailResponseDto.java
src/main/java/com/hanyang/arttherapy/dto/response/GallerySimpleDto.java
src/main/java/com/hanyang/arttherapy/dto/response/ReviewResponseDto.java
src/main/java/com/hanyang/arttherapy/repository/ArtsRepository.java
src/main/java/com/hanyang/arttherapy/repository/FilesRepository.java
src/main/java/com/hanyang/arttherapy/repository/ReviewRepository.java
src/main/java/com/hanyang/arttherapy/service/ArtsService.java
src/main/java/com/hanyang/arttherapy/service/ReviewService.java
src/main/resources/application.yml

- closed #31 
- closed #32 
- 작품 상세 조회
- 댓글 조회
- 댓글 작성자 이름 마스킹 처리
- 파일 리스트 처리
- Postman 성공

[FEAT] 작품 상세 & 댓글 조회

---

src/main/java/com/hanyang/arttherapy/common/exception/exceptionType/GalleryExceptionType.java
src/main/java/com/hanyang/arttherapy/controller/GalleriesController.java
src/main/java/com/hanyang/arttherapy/domain/Galleries.java
src/main/java/com/hanyang/arttherapy/repository/GalleriesRepository.java
src/main/java/com/hanyang/arttherapy/service/GalleriesService.java

- closed #41
- 전시회 등록 기능
- 전시회 전체 조회, 상세 조회 기능
- 전시회 수정 기능
- 전시회 삭제 기능
- GalleryExceptionType.java 적용
- 정상 등록, 조회, 수정, 삭제 확인
- 존재하지 않는 ID 접근 시 예외 응답 확인
- Postman 성공 / url - /api 수정 전 테스트 결과

[FEAT] 전시회 전체 기능 통합 및 예외 처리 적용

---

src/main/java/com/hanyang/arttherapy/controller/GalleriesController.java
src/main/java/com/hanyang/arttherapy/domain/Galleries.java
src/main/java/com/hanyang/arttherapy/dto/request/GalleriesRequestDto.java
src/main/java/com/hanyang/arttherapy/dto/response/GalleriesResponseDto.java
src/main/java/com/hanyang/arttherapy/service/GalleriesService.java

- closed #41
- 전시회 등록 기능
- 전시회 전체 조회, 상세 조회 기능
- 전시회 수정 기능
- 전시회 삭제 기능
- GalleryExceptionType.java 적용
- 정상 등록, 조회, 수정, 삭제 확인
- 존재하지 않는 ID 접근 시 예외 응답 확인
- Postman 성공 / url - /api 수정 전 테스트 결과

[REFACTOR] 전시회 기능 재구현

---

build.gradle
src/main/java/com/hanyang/arttherapy/common/init/DirectoryInit.java
src/main/java/com/hanyang/arttherapy/service/FileStorageService.java
src/main/java/com/hanyang/arttherapy/service/LocalFileStorageService.java
src/main/java/com/hanyang/arttherapy/service/S3FileStorageService.java

- closed #56 
- CloudFront URL과 파일 URL 조합
- 해당 사항 없음

[FEAT] 파일 URL 자동 조합 기능

---

Dockerfile
src/main/java/com/hanyang/arttherapy/domain/Galleries.java
src/main/java/com/hanyang/arttherapy/domain/UsersHistory.java
src/main/java/com/hanyang/arttherapy/service/ReviewService.java
src/main/resources/application.yml

- closed #65 
- Dockerfile 추가
- 엔티티 테이블 설정 스네이크 케이스로 변경
- 로컬 파일 서비스를 FileStorageService 인터페이스로 변경
- yml 뎁스 수정
- 엔티티 컬럼 명명 규칙 일관성 유지
- 해당 사항 없음

[DEPLOY] Dockerfile 추가

---

src/main/java/com/hanyang/arttherapy/controller/ArtsController.java
src/main/java/com/hanyang/arttherapy/controller/ReviewController.java
src/main/java/com/hanyang/arttherapy/domain/Arts.java
src/main/java/com/hanyang/arttherapy/domain/Galleries.java
src/main/java/com/hanyang/arttherapy/dto/request/ReviewRequestDto.java
src/main/java/com/hanyang/arttherapy/dto/response/ArtsListResponseDto.java
src/main/java/com/hanyang/arttherapy/dto/response/ArtsResponseDto.java
src/main/java/com/hanyang/arttherapy/dto/response/ReviewResponseDto.java
src/main/java/com/hanyang/arttherapy/repository/ArtsRepository.java
src/main/java/com/hanyang/arttherapy/repository/ReviewRepository.java
src/main/java/com/hanyang/arttherapy/service/ArtsService.java
src/main/java/com/hanyang/arttherapy/service/GalleriesService.java
src/main/java/com/hanyang/arttherapy/service/ReviewService.java

- closed #62 
-
- 기존 API 명세와 맞지 않은 부분 수정

[REFACTOR] 작품 조회 및 댓글 기능 API 수정

---

src/main/java/com/hanyang/arttherapy/repository/ArtsRepository.java
src/main/java/com/hanyang/arttherapy/repository/ReviewRepository.java
src/main/java/com/hanyang/arttherapy/service/ArtsService.java

- closed #68 
- 페이지네이션 수정
- Repository 주석 처리

[REFACTOR] 페이지네이션 수정 및 Repository 주석

---

src/main/java/com/hanyang/arttherapy/controller/ArtsController.java
src/main/java/com/hanyang/arttherapy/controller/ReviewController.java
src/main/java/com/hanyang/arttherapy/domain/ArtArtistRel.java
src/main/java/com/hanyang/arttherapy/domain/Arts.java
src/main/java/com/hanyang/arttherapy/domain/Galleries.java
src/main/java/com/hanyang/arttherapy/domain/Reviews.java
src/main/java/com/hanyang/arttherapy/dto/request/GalleriesRequestDto.java
src/main/java/com/hanyang/arttherapy/dto/request/ReviewRequestDto.java
src/main/java/com/hanyang/arttherapy/dto/response/ArtsListResponseDto.java
src/main/java/com/hanyang/arttherapy/dto/response/ArtsResponseDto.java
src/main/java/com/hanyang/arttherapy/dto/response/ReviewResponseDto.java
src/main/java/com/hanyang/arttherapy/repository/ArtArtistRelRepository.java
src/main/java/com/hanyang/arttherapy/repository/ArtsRepository.java
src/main/java/com/hanyang/arttherapy/repository/GalleriesRepository.java
src/main/java/com/hanyang/arttherapy/repository/ReviewRepository.java
src/main/java/com/hanyang/arttherapy/service/ArtsService.java
src/main/java/com/hanyang/arttherapy/service/GalleriesService.java
src/main/java/com/hanyang/arttherapy/service/ReviewService.java

[REFACTOR] 엔티티 및 서비스 로직 수정

---

src/main/java/com/hanyang/arttherapy/common/exception/exceptionType/ArtsExceptionType.java
src/main/java/com/hanyang/arttherapy/controller/ArtsController.java
src/main/java/com/hanyang/arttherapy/controller/ReviewController.java
src/main/java/com/hanyang/arttherapy/domain/Galleries.java
src/main/java/com/hanyang/arttherapy/dto/request/GalleriesRequestDto.java
src/main/java/com/hanyang/arttherapy/dto/response/ArtsListResponseDto.java
src/main/java/com/hanyang/arttherapy/dto/response/ArtsResponseDto.java
src/main/java/com/hanyang/arttherapy/repository/ArtArtistRelRepository.java
src/main/java/com/hanyang/arttherapy/repository/ArtsRepository.java
src/main/java/com/hanyang/arttherapy/repository/GalleriesRepository.java
src/main/java/com/hanyang/arttherapy/repository/ReviewRepository.java
src/main/java/com/hanyang/arttherapy/service/ArtsService.java
src/main/java/com/hanyang/arttherapy/service/GalleriesService.java
src/main/java/com/hanyang/arttherapy/service/ReviewService.java

- closed #76 
- ReviewService 수정
- ArtsService 수정
- ReviewController 수정
- ArtsController 수정
- ArtsListResponseDto 수정
- ArtsResponseDto 수정
- ArtsRepository 수정
- ReviewRepository 수정

[REFACTOR] galleriesNo 수정에 따른 서비스 및 컨트롤러 수정

---

src/main/java/com/hanyang/arttherapy/service/ReviewService.java

[REFACTOR] 하드코딩된 유저 ID 삭제 및 수정

---

src/main/java/com/hanyang/arttherapy/common/aws/config/AmazonConfig.java
src/main/java/com/hanyang/arttherapy/common/config/SecurityConfig.java
src/main/java/com/hanyang/arttherapy/controller/ArtistController.java
src/main/java/com/hanyang/arttherapy/service/S3FileStorageService.java
src/main/resources/application-dev.yml
src/main/resources/application.yml

- closed #80 
- 배포를 위한 시큐리티 설정 추가
- yml 설정 변경
- 작가 엔드포인트 변경
- 해당 사항 없음

[DEPLOY] 배포를 위한 시큐리티 설정 추가

---

src/main/java/com/hanyang/arttherapy/controller/HealthCheckController.java

- closed #80 
- 로드밸런스 헬스체크 API 추가
- 해당 사항 없음

[DEPLOY] deploy/#80

---

src/main/java/com/hanyang/arttherapy/controller/ArtistController.java

- API 경로 누락 수정
- API 경로 누락 수정
- 해당 사항 없음

[CHORE] 경로 누락 수정

---

src/main/java/com/hanyang/arttherapy/common/exception/exceptionType/ReviewException.java
src/main/java/com/hanyang/arttherapy/controller/ArtsController.java
src/main/java/com/hanyang/arttherapy/controller/ReviewController.java
src/main/java/com/hanyang/arttherapy/dto/request/GalleriesRequestDto.java
src/main/java/com/hanyang/arttherapy/dto/request/ReviewRequestDto.java
src/main/java/com/hanyang/arttherapy/dto/response/ArtsListResponseDto.java
src/main/java/com/hanyang/arttherapy/dto/response/ReviewResponseDto.java
src/main/java/com/hanyang/arttherapy/repository/ArtsRepository.java
src/main/java/com/hanyang/arttherapy/service/ArtsService.java
src/main/java/com/hanyang/arttherapy/service/ReviewService.java

- closed #87
- Dto @Builder 삭제
- 서비스단 에러처리
- 리뷰 조회 userNo추가
- 리뷰 filesNo이 비어있을 경우 빈 리스트로 응답
- ArtsController 조회 수정
- 리뷰 미로그인 유저 등록 기능 추가
- 리뷰 유저 이름 마스킹 처리 수정
-

[REFACTOR] 리뷰 CRUE 기능 개선 및 미로그인 사용자 댓글 등록 기능 추가

---

src/main/java/com/hanyang/arttherapy/controller/MyPageController.java
src/main/java/com/hanyang/arttherapy/dto/response/MyInfoResponseDto.java
src/main/java/com/hanyang/arttherapy/dto/response/MyPostResponseDto.java
src/main/java/com/hanyang/arttherapy/dto/response/MyReviewResponseDto.java
src/main/java/com/hanyang/arttherapy/repository/ArtsRepository.java
src/main/java/com/hanyang/arttherapy/service/MyPageService.java

- Closes #93 
- 마이페이지 나의 정보 조회
- 마이페이지 나의 작품 조회
- 마이페이지 나의 댓글 조회
- ArtsRepository 코드 수정
-

[FEAT] 마이페이지 기능 구현

---

src/main/java/com/hanyang/arttherapy/common/exception/exceptionType/AdminArtsExceptionType.java
src/main/java/com/hanyang/arttherapy/controller/AdminArtsController.java
src/main/java/com/hanyang/arttherapy/dto/request/AdminArtsRequestDto.java
src/main/java/com/hanyang/arttherapy/dto/response/AdminArtsDetailResponseDto.java
src/main/java/com/hanyang/arttherapy/dto/response/AdminArtsListResponseDto.java
src/main/java/com/hanyang/arttherapy/repository/ArtArtistRelRepository.java
src/main/java/com/hanyang/arttherapy/service/AdminArtsService.java

- Closes #95 
- 작품 등록
- 작품 수정()
- 작품 삭제
- 작품 조회
- 작품 상세조회
- ArtArtistRelRepository 코드 수정
-

[FEAT] 작품 기능

---

src/main/java/com/hanyang/arttherapy/common/exception/exceptionType/ProfessorExceptionType.java
src/main/java/com/hanyang/arttherapy/controller/ProfessorsController.java
src/main/java/com/hanyang/arttherapy/domain/Professors.java
src/main/java/com/hanyang/arttherapy/dto/request/ProfessorsRegisterRequestDto.java
src/main/java/com/hanyang/arttherapy/dto/request/ProfessorsRequestDto.java
src/main/java/com/hanyang/arttherapy/dto/response/ProfessorsResponseDto.java
src/main/java/com/hanyang/arttherapy/repository/ProfessorsRepository.java
src/main/java/com/hanyang/arttherapy/service/ProfessorsService.java

- Closes #104 
- 교수진 등록
- 교수진 전체조회 
- 교수진 상세조회
- 교수진 이름 검색
- 교수진 수정
- 교수진 삭제
-

[FEAT] 작품 기능 #96

---

src/main/java/com/hanyang/arttherapy/controller/GalleriesController.java
src/main/java/com/hanyang/arttherapy/domain/Galleries.java
src/main/java/com/hanyang/arttherapy/dto/request/GalleriesRequestDto.java
src/main/java/com/hanyang/arttherapy/dto/response/GalleriesResponseDto.java
src/main/java/com/hanyang/arttherapy/service/GalleriesService.java

-Closes #111 
- 성공 메세지 수정
- 전시회 일정 타입 수정
-

[REFACTOR] 전시회 성공 메세지 수정

---

src/main/java/com/hanyang/arttherapy/controller/ProfessorsController.java
src/main/java/com/hanyang/arttherapy/service/ProfessorsService.java

-Closes #116 
- 교수진 이름 검색 기능 삭제 
-

[REFACTOR] 교수진 수정

---

src/main/java/com/hanyang/arttherapy/service/ReviewService.java
src/main/java/com/hanyang/arttherapy/service/UserService.java

- 관리자 댓글 삭제 기능
- 관리자 모든 댓글 삭제 가능 기능
- UserService 복구
-

[FEAT] 관리자 댓글

---

src/main/java/com/hanyang/arttherapy/controller/MyPageController.java
src/main/java/com/hanyang/arttherapy/repository/ReviewRepository.java
src/main/java/com/hanyang/arttherapy/service/MyPageService.java

- Closed #128 
- 내 댓글 조회 
- 검색기능(작품명 + 댓글내용)
- 페이지네이션 (5개씩)
-

[FEAT] 마이페이지 댓글 

---

src/main/java/com/hanyang/arttherapy/common/exception/exceptionType/AdminArtsExceptionType.java
src/main/java/com/hanyang/arttherapy/controller/AdminArtsController.java
src/main/java/com/hanyang/arttherapy/repository/ArtsRepository.java
src/main/java/com/hanyang/arttherapy/service/AdminArtsService.java

- Closed #133 
- 필터[작품명, 작가명] + 검색

[FEAT] 관리자작품 검색기능

---

src/main/java/com/hanyang/arttherapy/common/exception/exceptionType/GalleryExceptionType.java
src/main/java/com/hanyang/arttherapy/controller/GalleriesController.java
src/main/java/com/hanyang/arttherapy/controller/ProfessorsController.java
src/main/java/com/hanyang/arttherapy/service/GalleriesService.java
src/main/java/com/hanyang/arttherapy/service/ProfessorsService.java

- Closed #136 
- 교수진 Role 비교
- 전시회 Role 비교
-

[REFACTOR] 전시회, 교수진 토큰 수정

---

src/main/java/com/hanyang/arttherapy/controller/MyPageController.java
src/main/java/com/hanyang/arttherapy/dto/request/MypageUpdateRequest.java
src/main/java/com/hanyang/arttherapy/service/MyPageService.java

- Closed #144 
- [REFACTOR] 마이페이지 수정 Response 수정
-

[REFACTOR] 마이페이지 수정 Response 수정

---

src/main/java/com/hanyang/arttherapy/dto/response/userResponse/UserDetailDto.java
src/main/java/com/hanyang/arttherapy/service/AdminUserService.java
src/main/java/com/hanyang/arttherapy/service/UserService.java

- closed #146 
-  관리자 페이지내 회원 상세 정보 조회 시 비밀번호 삭제

[FIX] 관리자 페이지내 회원 상세 정보 조회 시 비밀번호 삭제

---

src/main/java/com/hanyang/arttherapy/controller/MyPageController.java
src/main/java/com/hanyang/arttherapy/dto/response/MyInfoResponseDto.java
src/main/java/com/hanyang/arttherapy/service/MyPageService.java

- Closed #148 
- 조회, 수정 할때 userid 전송
-

[FEAT] 마이페이지 정보조회

---

src/main/java/com/hanyang/arttherapy/common/filter/JwtAuthenticationFilter.java
src/main/java/com/hanyang/arttherapy/common/util/JwtUtil.java
src/main/java/com/hanyang/arttherapy/domain/RefreshToken.java
src/main/java/com/hanyang/arttherapy/repository/RefreshTokenRepository.java
src/main/java/com/hanyang/arttherapy/service/UserService.java

[REFACTOR]인증/인가 수정

---

src/main/java/com/hanyang/arttherapy/dto/request/MypageUpdateRequest.java
src/main/java/com/hanyang/arttherapy/service/MyPageService.java

- closed #153 
- 유저에서 학번을 입력하면 작가로 변경
- 작가에서 학번을 null하면 유저로 변경
-

[FIX] 마이페이지 role 변경

---

src/main/java/com/hanyang/arttherapy/common/config/SecurityConfig.java
src/main/java/com/hanyang/arttherapy/common/exception/exceptionType/UserException.java
src/main/java/com/hanyang/arttherapy/common/filter/JwtAuthenticationFilter.java
src/main/java/com/hanyang/arttherapy/domain/RefreshTokens.java
src/main/java/com/hanyang/arttherapy/domain/Users.java
src/main/java/com/hanyang/arttherapy/domain/UsersHistory.java
src/main/java/com/hanyang/arttherapy/domain/enums/Role.java
src/main/java/com/hanyang/arttherapy/repository/RefreshTokenRepository.java
src/main/java/com/hanyang/arttherapy/repository/UserRepository.java
src/main/java/com/hanyang/arttherapy/service/AdminUserService.java
src/main/java/com/hanyang/arttherapy/service/MyPageService.java
src/main/java/com/hanyang/arttherapy/service/UserService.java

#115 
- 로그아웃시 refreshToken삭제(ip, userAgent, cookie)
- 회원탈퇴 에러메세지 일부 수정

[REFACTOR] 로그아웃, 탈퇴 수정

---

src/main/java/com/hanyang/arttherapy/service/MyPageService.java

마이페이지 이메일인증 exceptionType 변경
- closed #161 
- 마이페이지 이메일인증 exceptionType 변경
-

[FIX] 마이페이지 이메일인증 exceptionType 변경

---

src/main/java/com/hanyang/arttherapy/common/config/SecurityConfig.java
src/main/java/com/hanyang/arttherapy/dto/response/ArtsListResponseDto.java
src/main/java/com/hanyang/arttherapy/dto/response/MyReviewResponseDto.java
src/main/java/com/hanyang/arttherapy/dto/response/ReviewResponseDto.java
src/main/java/com/hanyang/arttherapy/repository/ArtArtistRelRepository.java
src/main/java/com/hanyang/arttherapy/repository/ArtsRepository.java
src/main/java/com/hanyang/arttherapy/repository/ReviewRepository.java
src/main/java/com/hanyang/arttherapy/service/ArtsService.java
src/main/java/com/hanyang/arttherapy/service/MyPageService.java
src/main/java/com/hanyang/arttherapy/service/NoticesService.java
src/main/java/com/hanyang/arttherapy/service/ReviewService.java
src/main/java/com/hanyang/arttherapy/service/S3FileStorageService.java

- closed #158 
- reviewsNo 및 파일 URL 수정

[REFACTOR] reviewsNo 및 파일 URL 수정

---

src/main/java/com/hanyang/arttherapy/dto/response/AdminArtsListResponseDto.java
src/main/java/com/hanyang/arttherapy/service/AdminArtsService.java

- closed #172 
- 전체 조회 response 수정
-

[REFACTOR] 관리자 작품

---

src/main/java/com/hanyang/arttherapy/service/AdminUserService.java
src/main/java/com/hanyang/arttherapy/service/ArtsService.java
src/main/java/com/hanyang/arttherapy/service/ReviewService.java
src/main/java/com/hanyang/arttherapy/service/S3FileStorageService.java

- closed #174 
- 작품 및 댓글 서비스 수정
-

[FIX] 작품 및 댓글 서비스 수정

---

src/main/java/com/hanyang/arttherapy/service/NoticesService.java
src/test/java/com/hanyang/arttherapy/service/LocalFileStorageServiceTest.java

- closed #177 
-  게시판 페이지네이션 수정
-

[FIX] 게시판 페이지네이션 수정

---

src/main/java/com/hanyang/arttherapy/common/config/SecurityConfig.java
src/main/java/com/hanyang/arttherapy/controller/ArtistController.java
src/main/java/com/hanyang/arttherapy/dto/response/artistResponse/ArtistResponseDto.java
src/main/java/com/hanyang/arttherapy/dto/response/artistResponse/ArtistScrollResponseDto.java
src/main/java/com/hanyang/arttherapy/dto/response/userResponse/UserDetailDto.java
src/main/java/com/hanyang/arttherapy/repository/ArtistsRepositoryImpl.java
src/main/java/com/hanyang/arttherapy/service/ArtistsService.java
src/main/java/com/hanyang/arttherapy/service/UserService.java

#105
- 관리자 페이지 작가 조회 무한스크롤(10개씩 나눠서 정보보내기)

[REFACTOR]관리자 페이지 작가 조회

---

src/main/java/com/hanyang/arttherapy/dto/request/ProfessorsRequestDto.java
src/main/java/com/hanyang/arttherapy/dto/response/ProfessorsResponseDto.java
src/main/java/com/hanyang/arttherapy/service/ProfessorsService.java

- closed #182 
- filesurl-> url
- 파일 배열로
-

[FIX] 관리자 교수진 url 컬럼 수정

---

src/main/java/com/hanyang/arttherapy/common/exception/exceptionType/GalleryExceptionType.java
src/main/java/com/hanyang/arttherapy/repository/GalleriesRepository.java
src/main/java/com/hanyang/arttherapy/service/GalleriesService.java

- closed #184 
- 전시회 등록 날짜 검사
-

[REFACTOR] 관리자 전시회 날짜

---

src/main/java/com/hanyang/arttherapy/dto/request/admin/AdminArtsPatchRequestDto.java
src/main/java/com/hanyang/arttherapy/service/AdminArtsService.java

- closed #189 
- artistList -> artists
-

[FIX] 관리자 작품 리스트명 수정

---

src/main/java/com/hanyang/arttherapy/service/ArtistsService.java
src/main/java/com/hanyang/arttherapy/service/UserService.java

#115
- 회원 로그인 조건 수정
-로그인 리프레시토큰 추가
-로그아웃 리프레시토큰 삭제

[REFACTOR]회원 로그인 수정

---

src/main/java/com/hanyang/arttherapy/controller/ReviewController.java

- closed #192 
- 댓글 페이지네이션 4개로 수정
-

[FIX] 댓글 페이지네이션 수정

---

src/main/java/com/hanyang/arttherapy/dto/response/ArtsResponseDto.java

- closed #197 
- 작품 상세 조회 galleriesTitle, galleriesStartDate 추가
-

[REFACTOR] 작품 상세 조회 galleriesTitle, galleriesStartDate 추가

---

src/main/java/com/hanyang/arttherapy/controller/ProfessorViewController.java
src/main/java/com/hanyang/arttherapy/service/ProfessorViewService.java

- closed #196 
-  교수진 정보 조회 (모든 정보)
-

[FEAT] 교수진 소개

---

src/main/java/com/hanyang/arttherapy/service/ProfessorViewService.java

- closed #203 
- 교수진 url 관련 file 쪽 수정
-

[FIX] 교수진 URL 수정

---

src/main/java/com/hanyang/arttherapy/controller/ReviewController.java

[REFACTOR] 댓글 정렬 최신순 수정

---

src/main/java/com/hanyang/arttherapy/repository/ArtsRepository.java

-#closed #213 
- 관리자 작품 조회 정렬 수정
-

[REFACTOR] 관리자 작품 조회 정렬 수정

---

src/main/java/com/hanyang/arttherapy/service/ArtsService.java

[REFACTOR] 작품 전체 조회시 일부 작품 중복 반환 제거

---

src/main/java/com/hanyang/arttherapy/common/config/SecurityConfig.java
src/main/java/com/hanyang/arttherapy/common/exception/exceptionType/GalleryExceptionType.java
src/main/java/com/hanyang/arttherapy/controller/GalleriesPublicController.java
src/main/java/com/hanyang/arttherapy/service/GalleriesService.java

- closed #227 
-  전시회 정보 조회 기능 구현
-

[FEAT] 전시회 정보 조회 기능

---

src/main/java/com/hanyang/arttherapy/service/MyPageService.java

- closed #229 
- 관리자나 테스터가 학번을 변경 하더라도 무조건 자신의 role를 유지
-

[REFACTOR] 마이페이지 role

---

src/main/java/com/hanyang/arttherapy/repository/ArtArtistRelRepository.java
src/main/java/com/hanyang/arttherapy/service/ArtsService.java

[REFACTOR] 작품 조회시 기수 목록 수정
